name: project_environment
dependencies:
  - python=3.5.2
  - scikit-learn
  - ipykernel=4.6.1
  - pip:
    - azure-ml-api-sdk==0.1.0a10
    - https://azuremldownloads.blob.core.windows.net/wheels/latest/azureml.assets-1.0.0-py3-none-any.whl?sv=2016-05-31&si=ro-2017&sr=c&sig=xnUdTm0B%2F%2FfknhTaRInBXyu2QTTt8wA3OsXwGVgU%2BJk%3D
